# -*- coding: utf-8 -*-
"""test_bad.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L96RkzoVd_mjiJU0a__tFDTroBCRRDca
"""

import numpy as np
import os

name = input("Enter name: ")
query = f"SELECT * FROM users WHERE name = '{name}'"  # SQL injection!
os.system("rm -rf /")  # Very dangerous!